# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.6.2"
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos6.4"
  config.vm.hostname = "centos64"
  config.vm.provision :docker do |d|
    d.pull_images "centos:6.4"
  end
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
