# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.6.2"
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provider "docker" do |d|
    d.vagrant_vagrantfile = "proxy-vm/Vagrantfile"
    d.build_dir = "."
  end
  config.vm.network :forwarded_port, guest: 80, host: 8080
end
